name: Demos

on:
  push:
    branches: [ master ]
    paths:
      - 'demo/**'
      - 'lib/**'
      - '.github/**'
      - 'Rakefile'
  pull_request:
    branches: ['**']
    paths:
      - 'demo/**'
      - '.github/**'
      - 'Rakefile'

jobs:
  demos:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [ head ]
    name: Ruby ${{ matrix.ruby }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler: none
      - name: Install dependencies
        run: gem install dotcfg fiber_scheduler
      - name: Run all demos on CRuby 3.x
        run: rake demo
  jvm_demos:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [ '3.1', head, jruby, truffleruby ]
    name: Ruby ${{ matrix.ruby }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
	  bundler: none
      - name: Install dependencies
        run: gem install dotcfg
      - name: Run JVM compatible demos
        run: rake jvm_demo

  bundler_tr:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [ truffleruby ]
    name: Ruby ${{ matrix.ruby }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Install rubygems-update
        run: gem install rubygems-update
      - name: Update RubyGems
        run: update_rubygems
      - name: Install dependencies
        run: bundle install
      - name: Run JVM compatible demos
        run: rake jvm_demo
