name: Demos

on:
  push:
    branches: [ master ]
    paths:
      - 'demo/**'
      - '.github/**'
      - 'Rakefile'
  pull_request:
    branches: ['**']
    paths:
      - 'demo/**'
      - '.github/**'
      - 'Rakefile'

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # ruby: [ head, jruby, truffleruby ]
        ruby: [ '3.1', head ]
    name: Ruby ${{ matrix.ruby }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler: none
      - name: Install dependencies
        run: gem install compsci dotcfg fiber_scheduler
      - name: Run all demos
        run: rake demo
