name: Tests

on:
  push:
    branches: [ master ]
    paths:
      - 'lib/**'
      - 'test/**'
      - '.github/**'
      - 'Rakefile'
  pull_request:
    branches: ['**']
    paths:
      - 'lib/**'
      - 'test/**'
      - '.github/**'
      - 'Rakefile'

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [ head, jruby, truffleruby ]
    name: Ruby ${{ matrix.ruby }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler: none
      - name: Install dependencies
        run: gem install compsci
      - name: Run tests
        run: rake test
